-- Generated from Profilarr v1 YAML on 2026-08-28. Do not edit prior operations; append a new operation instead.

-- Tags
INSERT INTO tags (name) VALUES ('Radarr');
INSERT INTO tags (name) VALUES ('Release Title');
INSERT INTO tags (name) VALUES ('Sonarr');
INSERT INTO tags (name) VALUES ('audio');
INSERT INTO tags (name) VALUES ('chanel');
INSERT INTO tags (name) VALUES ('channel');
INSERT INTO tags (name) VALUES ('dts');
INSERT INTO tags (name) VALUES ('edition');
INSERT INTO tags (name) VALUES ('encoding');
INSERT INTO tags (name) VALUES ('language');
INSERT INTO tags (name) VALUES ('release group');
INSERT INTO tags (name) VALUES ('size');
INSERT INTO tags (name) VALUES ('video');

-- Regular expressions
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('10bit', '10[.-]?bit', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('10bit', 'encoding');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('3.0ch', '[^0-9]3[ .]0\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('3.0ch', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('3.0ch', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('3D', '(?<=\b[12]\d{3}\b).*\b(3d|sbs|half[ .-]ou|half[ .-]sbs)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('3D', 'video');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('4.0ch', '[^0-9]4[ .]0\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('4.0ch', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('4.0ch', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('5.1 Surround', '[^0-9]5[ .][0-1]\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('5.1 Surround', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('5.1 Surround', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('6.1 Surround', '[^0-9]6[ .][0-1]\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('6.1 Surround', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('6.1 Surround', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('7.1 Surround', '[^0-9][7-8][ .][0-1]\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('7.1 Surround', 'Radarr');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('7.1 Surround', 'Sonarr');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('AAC', '\bAAC(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('AAC', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('ATMOS', '\b(ATMOS|DDPA)(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('ATMOS', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('BD3D', '\b(BD3D)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('BD3D', 'video');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('BluRay3D', '\b(BluRay3D)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('BluRay3D', 'video');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('DTS', '\bDTS(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('DTS', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('DTS', 'dts');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Dolby Digital Plus', '\bDD[P+](?!A)|\b(e[-_. ]?ac-?3)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Dolby Digital Plus', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Dolby Digital', '\bDD[^a-z+]|(?<!e-)\b(ac-?3)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Dolby Digital', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('FLAC', '\bFLAC(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('FLAC', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('High Channel Count', '[^0-9][5-9][ .][0-1]\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('High Channel Count', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('High Channel Count', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('MULTI', '\bMULTI\b', NULL, 'Multi audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('MULTI', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Mono', '[^0-9]1[ .]0\b|\bMono\b|\[PCM \]', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Mono', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Mono', 'chanel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('PCM', '\b(l?)PCM(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('PCM', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Remaster', 'Remaster', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Remaster', 'edition');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Special Edition', '(?<!^|{)\b(extended|uncut|directors|special|unrated|uncensored|cut|version|edition)(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Special Edition', 'edition');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Stereo', '(?<!repac)[^0-9]2[ .]0\b|\bStereo\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Stereo', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Stereo', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Team Amen', '\b(Amen)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Team Amen', 'release group');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Team QTZ', '\b(QTZ)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Team QTZ', 'release group');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Team TyHD', '\b(TyHD)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Team TyHD', 'release group');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('TrueHD-ATMOS', '\b(True[ .-]?HD|ATMOS|DDPA)(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('TrueHD-ATMOS', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('TrueHD', 'True[ .-]?HD', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('TrueHD', 'audio');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('VF2', '\bVF2\b|(?=.*\bVFF\b)(?=.*\bVFQ\b)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('VF2', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('VFF', '\b(TRUEFRENCH|VFF)\b', NULL, 'French audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('VFF', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('VFI', '\b(VFI)\b', NULL, 'French international audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('VFI', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('VFO', '\b(VOF)\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('VFO', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('VFQ', '\b(VFQ|\d{3,4}p[ .]CAN|(?<=MULTi[ .])FR(A|ENCH))\b', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('VFQ', 'language');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('hi10p', 'hi10p', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('hi10p', 'encoding');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('x265', '[xh][ ._-]?265|\bHEVC(\b|\d)', NULL, '');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('x265', 'encoding');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('Low Channel Count', '(?:[^0-9]1[ .]0\b|\bMono\b|\[PCM \]|(?<!repac)[^0-9]2[ .]0\b|\bStereo\b|[^0-9]3[ .]0\b|[^0-9]4[ .]0\b)', NULL, 'Derived during v1-to-PCD migration from the existing Mono, Stereo, 3.0ch and 4.0ch regexes.');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Low Channel Count', 'audio');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Low Channel Count', 'channel');
INSERT INTO regular_expressions (name, pattern, regex101_id, description) VALUES ('OPUS (inline condition)', '\bOPUS(\b|\d)', NULL, 'Created during v1-to-PCD migration to preserve the inline OPUS pattern.');
INSERT INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('OPUS (inline condition)', 'audio');

-- Custom formats and tags
INSERT INTO custom_formats (name, description) VALUES ('1.0 Mono', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#10-mono)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('1.0 Mono', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('1.0 Mono', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('10bit', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#10bit)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('10bit', 'encoding');
INSERT INTO custom_formats (name, description) VALUES ('2.0 Stereo', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#20-stereo)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('2.0 Stereo', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('2.0 Stereo', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('3.0 Sound', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#30-sound)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('3.0 Sound', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('3.0 Sound', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('3D', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#3d)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('3D', 'video');
INSERT INTO custom_formats (name, description) VALUES ('4.0 Sound', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#40-sound)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('4.0 Sound', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('4.0 Sound', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('5.1 Surround', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#51-surround)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('5.1 Surround', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('5.1 Surround', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('6.1 Surround', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#61-surround)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('6.1 Surround', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('6.1 Surround', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('7.1 Surround', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#71-surround)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('7.1 Surround', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('7.1 Surround', 'channel');
INSERT INTO custom_formats (name, description) VALUES ('DTS', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('DTS', 'audio');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('DTS', 'dts');
INSERT INTO custom_formats (name, description) VALUES ('Dolby Digital Plus ATMOS', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#ddplus-atmos)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Dolby Digital Plus ATMOS', 'Radarr');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Dolby Digital Plus ATMOS', 'Release Title');
INSERT INTO custom_formats (name, description) VALUES ('Dolby Digital Plus', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#ddplus)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Dolby Digital Plus', 'Radarr');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Dolby Digital Plus', 'Release Title');
INSERT INTO custom_formats (name, description) VALUES ('Dolby Digital', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#dd)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Dolby Digital', 'audio');
INSERT INTO custom_formats (name, description) VALUES ('French Canadian', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('French Canadian', 'language');
INSERT INTO custom_formats (name, description) VALUES ('Language Not French', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Language Not French', 'language');
INSERT INTO custom_formats (name, description) VALUES ('Language Not Original', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Language Not Original', 'language');
INSERT INTO custom_formats (name, description) VALUES ('OPUS', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('OPUS', 'audio');
INSERT INTO custom_formats (name, description) VALUES ('Radarr - Size Balanced', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Radarr - Size Balanced', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Radarr - Size Compact', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Radarr - Size Compact', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Radarr - Size Not Balanced', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Radarr - Size Not Balanced', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Radarr - Size Not Compact', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Radarr - Size Not Compact', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Remaster', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#remaster)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Remaster', 'edition');
INSERT INTO custom_formats (name, description) VALUES ('Sonarr - Size Balanced', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Sonarr - Size Balanced', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Sonarr - Size Compact', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Sonarr - Size Compact', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Sonarr - Size Not Balanced', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Sonarr - Size Not Balanced', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Sonarr - Size Not Compact', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Sonarr - Size Not Compact', 'size');
INSERT INTO custom_formats (name, description) VALUES ('Special Edition', '[Custom format from TRaSH-Guides.](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats#special-edition)');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Special Edition', 'edition');
INSERT INTO custom_formats (name, description) VALUES ('Team Amen', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Team Amen', 'release group');
INSERT INTO custom_formats (name, description) VALUES ('Team QTZ', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Team QTZ', 'release group');
INSERT INTO custom_formats (name, description) VALUES ('Team TyHD', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('Team TyHD', 'release group');
INSERT INTO custom_formats (name, description) VALUES ('VF2', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('VF2', 'encoding');
INSERT INTO custom_formats (name, description) VALUES ('VFF', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('VFF', 'encoding');
INSERT INTO custom_formats (name, description) VALUES ('VFI', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('VFI', 'encoding');
INSERT INTO custom_formats (name, description) VALUES ('VFO', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('VFO', 'encoding');
INSERT INTO custom_formats (name, description) VALUES ('x265', '');
INSERT INTO custom_format_tags (custom_format_name, tag_name) VALUES ('x265', 'encoding');

-- Conditions
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('1.0 Mono', 'Mono', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('1.0 Mono', 'Mono', 'Mono');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('1.0 Mono', 'Not 3.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('1.0 Mono', 'Not 3.0ch', '3.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('1.0 Mono', 'Not 4.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('1.0 Mono', 'Not 4.0ch', '4.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('1.0 Mono', 'Not High Channel Count', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('1.0 Mono', 'Not High Channel Count', 'High Channel Count');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('10bit', '10bit', 'release_title', 'all', 0, 0);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('10bit', '10bit', '10bit');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('10bit', 'hi10p', 'release_title', 'all', 0, 0);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('10bit', 'hi10p', 'hi10p');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('2.0 Stereo', 'Stereo', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('2.0 Stereo', 'Stereo', 'Stereo');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('2.0 Stereo', 'Not 3.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('2.0 Stereo', 'Not 3.0ch', '3.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('2.0 Stereo', 'Not 4.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('2.0 Stereo', 'Not 4.0ch', '4.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('2.0 Stereo', 'Not High Channel Count', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('2.0 Stereo', 'Not High Channel Count', 'High Channel Count');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('2.0 Stereo', 'Not Mono', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('2.0 Stereo', 'Not Mono', 'Mono');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3.0 Sound', '3.0ch', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3.0 Sound', '3.0ch', '3.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3.0 Sound', 'Not Mono', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3.0 Sound', 'Not Mono', 'Mono');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3.0 Sound', 'Not Stereo', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3.0 Sound', 'Not Stereo', 'Stereo');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3.0 Sound', 'Not 4.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3.0 Sound', 'Not 4.0ch', '4.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3.0 Sound', 'Not High Channel Count', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3.0 Sound', 'Not High Channel Count', 'High Channel Count');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3D', '3D', 'release_title', 'all', 0, 0);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3D', '3D', '3D');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3D', 'BluRay3D', 'release_title', 'all', 0, 0);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3D', 'BluRay3D', 'BluRay3D');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('3D', 'BD3D', 'release_title', 'all', 0, 0);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('3D', 'BD3D', 'BD3D');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('4.0 Sound', '4.0ch', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('4.0 Sound', '4.0ch', '4.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('4.0 Sound', 'Not Mono', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('4.0 Sound', 'Not Mono', 'Mono');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('4.0 Sound', 'Not Stereo', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('4.0 Sound', 'Not Stereo', 'Stereo');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('4.0 Sound', 'Not 3.0ch', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('4.0 Sound', 'Not 3.0ch', '3.0ch');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('4.0 Sound', 'Not High Channel Count', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('4.0 Sound', 'Not High Channel Count', 'High Channel Count');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('5.1 Surround', '5.1 Surround', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('5.1 Surround', '5.1 Surround', '5.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('5.1 Surround', 'Not 6.1 Surround', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('5.1 Surround', 'Not 6.1 Surround', '6.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('5.1 Surround', 'Not 7.1 Surround', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('5.1 Surround', 'Not 7.1 Surround', '7.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('6.1 Surround', '6.1 Surround', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('6.1 Surround', '6.1 Surround', '6.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('6.1 Surround', 'Not 7.1 Surround', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('6.1 Surround', 'Not 7.1 Surround', '7.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('7.1 Surround', '7.1 Surround', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('7.1 Surround', '7.1 Surround', '7.1 Surround');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('7.1 Surround', 'Not Low Channel Count', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('7.1 Surround', 'Not Low Channel Count', 'Low Channel Count');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('DTS', 'DTS', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('DTS', 'DTS', 'DTS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Dolby Digital Plus', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Dolby Digital Plus', 'Dolby Digital Plus');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'ATMOS', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'ATMOS', 'ATMOS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not TrueHD', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not TrueHD', 'TrueHD');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not DTS', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not DTS', 'DTS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not Basic Dolby Digital', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not Basic Dolby Digital', 'Dolby Digital');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not FLAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not FLAC', 'FLAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not AAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not AAC', 'AAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus ATMOS', 'Not PCM', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus ATMOS', 'Not PCM', 'PCM');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Dolby Digital Plus', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Dolby Digital Plus', 'Dolby Digital Plus');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Not TrueHD-ATMOS', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Not TrueHD-ATMOS', 'TrueHD-ATMOS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Not DTS', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Not DTS', 'DTS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Not FLAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Not FLAC', 'FLAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Not AAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Not AAC', 'AAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital Plus', 'Not PCM', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital Plus', 'Not PCM', 'PCM');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Basic Dolby Digital', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Basic Dolby Digital', 'Dolby Digital');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not Dolby Digital Plus', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not Dolby Digital Plus', 'Dolby Digital Plus');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not TrueHD-ATMOS', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not TrueHD-ATMOS', 'TrueHD-ATMOS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not DTS', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not DTS', 'DTS');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not FLAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not FLAC', 'FLAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not AAC', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not AAC', 'AAC');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Dolby Digital', 'Not PCM', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Dolby Digital', 'Not PCM', 'PCM');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('French Canadian', 'VFQ', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('French Canadian', 'VFQ', 'VFQ');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('French Canadian', 'No VF2', 'release_title', 'all', 1, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('French Canadian', 'No VF2', 'VF2');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language Not French', 'not Original French', 'language', 'all', 1, 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language Not French', 'not Original French', 'French', 0);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language Not Original', 'not Original Language', 'language', 'all', 1, 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language Not Original', 'not Original Language', 'Original', 0);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('OPUS', 'OPUS', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('OPUS', 'OPUS', 'OPUS (inline condition)');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Radarr - Size Balanced', 'Balanced Size', 'size', 'all', 0, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Radarr - Size Balanced', 'Balanced Size', 3221225472, 8589934592);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Radarr - Size Compact', 'Compact Size', 'size', 'all', 0, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Radarr - Size Compact', 'Compact Size', 0, 6442450944);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Radarr - Size Not Balanced', 'Balanced Size', 'size', 'all', 1, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Radarr - Size Not Balanced', 'Balanced Size', 0, 8589934592);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Radarr - Size Not Compact', 'Not Compact Size', 'size', 'all', 1, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Radarr - Size Not Compact', 'Not Compact Size', 0, 6442450944);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Remaster', 'Remaster', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Remaster', 'Remaster', 'Remaster');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Sonarr - Size Balanced', 'Balanced Size', 'size', 'all', 0, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Sonarr - Size Balanced', 'Balanced Size', 1073741824, 2147483648);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Sonarr - Size Compact', 'Compact Size', 'size', 'all', 0, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Sonarr - Size Compact', 'Compact Size', 0, 6442450944);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Sonarr - Size Not Balanced', 'Not Balanced Size', 'size', 'all', 1, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Sonarr - Size Not Balanced', 'Not Balanced Size', 0, 2147483648);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Sonarr - Size Not Compact', 'Not Compact Size', 'size', 'all', 1, 1);
INSERT INTO condition_sizes (custom_format_name, condition_name, min_bytes, max_bytes) VALUES ('Sonarr - Size Not Compact', 'Not Compact Size', 0, 2147483648);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Special Edition', 'Special Edition', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Special Edition', 'Special Edition', 'Special Edition');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Team Amen', 'Team Amen', 'release_group', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Team Amen', 'Team Amen', 'Team Amen');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Team QTZ', 'Team QTZ', 'release_group', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Team QTZ', 'Team QTZ', 'Team QTZ');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Team TyHD', 'Team TyHD', 'release_group', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Team TyHD', 'Team TyHD', 'Team TyHD');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('VF2', 'VF2', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('VF2', 'VF2', 'VF2');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('VFF', 'VFF', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('VFF', 'VFF', 'VFF');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('VFI', 'VFI', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('VFI', 'VFI', 'VFI');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('VFO', 'VFO', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('VFO', 'VFO', 'VFO');
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('x265', 'X265', 'release_title', 'all', 0, 1);
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('x265', 'X265', 'x265');

-- Custom format tests
INSERT INTO custom_format_tests (custom_format_name, title, type, should_match, description) VALUES ('French Canadian', 'Release Name (2004) MULTi (VFF-VO-VFQ) [1080p] MULTi x264', 'movie', 0, 'Migrated from v1 test id 1.');

-- Quality profiles, language and quality order
INSERT INTO quality_profiles (name, description, upgrades_allowed, minimum_custom_format_score, upgrade_until_score, upgrade_score_increment) VALUES ('Cinematic', '', 0, 0, 0, 1);
INSERT INTO quality_profile_languages (quality_profile_name, language_name, type) VALUES ('Cinematic', 'Original', 'must');
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'WEBDL-2160p', NULL, 0, 1, 1);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'WEBRip-2160p', NULL, 1, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'Bluray-2160p', NULL, 2, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'WEBDL-1080p', NULL, 3, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'WEBRip-1080p', NULL, 4, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'Bluray-1080p', NULL, 5, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Cinematic', 'HDTV-1080p', NULL, 6, 1, 0);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Dolby Digital Plus ATMOS', 'all', 900);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Dolby Digital Plus', 'all', 800);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Dolby Digital', 'all', 600);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'x265', 'all', 500);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'VFF', 'all', 350);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '5.1 Surround', 'all', 300);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Team QTZ', 'all', 300);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Team Amen', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Team TyHD', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'VFO', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'VFI', 'all', 200);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '7.1 Surround', 'all', 180);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '6.1 Surround', 'all', 150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'VF2', 'all', 150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '10bit', 'all', 120);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Remaster', 'all', 100);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '2.0 Stereo', 'all', -150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '4.0 Sound', 'all', -250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '3.0 Sound', 'all', -300);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '1.0 Mono', 'all', -400);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Language Not Original', 'all', -1000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Language Not French', 'all', -10000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'DTS', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'OPUS', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'French Canadian', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', '3D', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Radarr - Size Compact', 'radarr', 200);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Radarr - Size Not Balanced', 'radarr', -10000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Special Edition', 'radarr', 100);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Sonarr - Size Compact', 'sonarr', 200);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Cinematic', 'Sonarr - Size Not Balanced', 'sonarr', -10000);
INSERT INTO quality_profiles (name, description, upgrades_allowed, minimum_custom_format_score, upgrade_until_score, upgrade_score_increment) VALUES ('Compact', '', 0, 0, 0, 1);
INSERT INTO quality_profile_languages (quality_profile_name, language_name, type) VALUES ('Compact', 'Original', 'must');
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'WEBDL-2160p', NULL, 0, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'WEBRip-2160p', NULL, 1, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'Bluray-2160p', NULL, 2, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'WEBDL-1080p', NULL, 3, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'WEBRip-1080p', NULL, 4, 1, 0);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'Bluray-1080p', NULL, 5, 1, 1);
INSERT INTO quality_profile_qualities (quality_profile_name, quality_name, quality_group_name, position, enabled, upgrade_until) VALUES ('Compact', 'HDTV-1080p', NULL, 6, 1, 0);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Dolby Digital Plus ATMOS', 'all', 900);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Dolby Digital Plus', 'all', 800);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Dolby Digital', 'all', 600);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'x265', 'all', 500);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'VFF', 'all', 350);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '5.1 Surround', 'all', 300);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Team QTZ', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Team Amen', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Team TyHD', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'VFO', 'all', 250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'VFI', 'all', 200);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '7.1 Surround', 'all', 180);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '6.1 Surround', 'all', 150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'VF2', 'all', 150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '10bit', 'all', 120);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Remaster', 'all', 100);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '2.0 Stereo', 'all', -150);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '4.0 Sound', 'all', -250);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '3.0 Sound', 'all', -300);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '1.0 Mono', 'all', -400);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Language Not Original', 'all', -1000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Language Not French', 'all', -10000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'DTS', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'OPUS', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'French Canadian', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', '3D', 'all', -100000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Radarr - Size Not Compact', 'radarr', -10000);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Special Edition', 'radarr', 100);
INSERT INTO quality_profile_custom_formats (quality_profile_name, custom_format_name, arr_type, score) VALUES ('Compact', 'Sonarr - Size Not Compact', 'sonarr', -10000);
